---
title: "Getting started with mongolstats"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started with mongolstats}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
eval_site <- TRUE
if (requireNamespace("pkgdown", quietly = TRUE)) eval_site <- pkgdown::in_pkgdown()
if (eval_site && requireNamespace("curl", quietly = TRUE)) eval_site <- curl::has_internet()
knitr::opts_chunk$set(eval = eval_site, message = FALSE, warning = FALSE, error = TRUE)
if (eval_site) {
  options(mongolstats.retry_tries = 5L, mongolstats.timeout = 60)
  try(mongolstats::nso_cache_enable(), silent = TRUE)
}
```

```{r}
library(mongolstats)
library(dplyr)

# Point to new PXWeb API (default set on load)
nso_options(mongolstats.lang = "en")
```

## List tables

```{r}
itms <- nso_itms()
itms %>% dplyr::select(dplyr::any_of(c("tbl_id", "tbl_eng_nm", "strt_prd", "end_prd"))) %>% dplyr::slice_head(n = 5)
```

## Explore variables (codebook)

```{r}
vars <- nso_variables("DT_NSO_0300_001V2")
vars %>% dplyr::count(field)
vars %>% dplyr::filter(field %in% c("Sex","Age","Year")) %>% dplyr::slice_head(n = 10)
```

## Fetch data

```{r}
dat <- nso_data(
  tbl_id = "DT_NSO_0300_001V2",
  selections = list(Sex = "Total", Age = "Total", Year = "2024")
)

dat %>% dplyr::slice_head(n = 6)
```
