structure(list(method = "GET", url = "https://data.1212.mn/api/v1/mn/NSO/Economy%2C%20environment/Money%20and%20Finance/DT_NSO_0300_2024V02.px", 
    status_code = 400L, headers = structure(list(`cache-control` = "private,no-cache, must-revalidate Pragma: no-cache Expires: 0", 
        `content-type` = "text/html", `access-control-allow-origin` = "*", 
        `set-cookie` = "REDACTED", `x-powered-by` = "ASP.NET", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `content-security-policy` = "script-src 'self' 'unsafe-inline' 'unsafe-eval'", 
        `x-frame-options` = "SAMEORIGIN", `referrer-policy` = "same-origin", 
        `strict-transport-security` = "max-age=31536000; includeSubDomains; preload", 
        date = "Sun, 05 Oct 2025 08:13:21 GMT", `content-length` = "11"), class = "httr2_headers"), 
    body = charToRaw("Bad Request"), timing = c(redirect = 0, 
    namelookup = 1.7e-05, connect = 0, pretransfer = 8.4e-05, 
    starttransfer = 0.233876, total = 0.233904), cache = new.env(parent = emptyenv())), class = "httr2_response")
